version: "3.9"

services:
  dbd:
    build:
      context: .
      dockerfile: develop/dbd/Dockerfile
    image: dbd-avatica:latest
    volumes:
      - ".:/dbd"
    depends_on:
      - hpqs
    working_dir: /dbd
    environment:
      TEST_ONLINE: 'http://hpqs:8765'
    cap_add:
      - ALL
    privileged: true
    tty: true
    command: ['/bin/bash']
  # Hbase + Phoenix + QueryServer = HPQS
  hpqs:
    build:
        context: .
        dockerfile: develop/hpqs/Dockerfile
    image: avatica-hbase-1.4
    volumes:
      - "./develop/hpqs/hbase-site.xml:/hpqs/hbase-1.4.14/conf/hbase-site.xml"
    working_dir: /hpqs
    environment:
      JAVA_HOME: '/usr/local/openjdk-8'
      HBASE_HOME: '/hpqs/hbase-1.4.14'
      HBASE_CONF_DIR: '/hpqs/hbase-1.4.14/conf'
      PHOENIX_LIB_DIR: '/hpqs/apache-phoenix-4.15.0-HBase-1.4-bin'
    cap_add:
      - ALL
    privileged: true
    tty: true
    command: ['/bin/bash', '/hpqs/start.sh']
